### ISSUE TITLE
Cursor sometimes does not move the view to scrollCol 0

### ISSUE THREAD

**Issue by aaxu** [google/ci_edit#99] opened 2017-10-17 18:56 UTC
Not sure why this happens, but it's looking like it's happening if I am on the last row, move the view to the right, then move it back to the left, scrollCol gets capped at 1. I also can only reproduce this if I save the file with the cursor on the last row, then reopen it.

![highlight_bug](https://user-images.githubusercontent.com/19481525/31683539-1a97e6d4-b332-11e7-98fe-a53ddce074bc.gif)

**Comment by dschuyler** [comment] 2017-10-19 03:00
I made some fixes for using home/end and for spell checking. Do those fix this issue?
If not, does the editor no longer allow scrolling to column 1 or does it just not do it automatically?
I'm wondering if I'm misunderstanding because I haven't exactly reproduced the issue.

**Comment by aaxu** [comment] 2017-10-19 03:24
Okay I think you fixed this. Another issue I found was that if you have a word that is longer than the width of the screen, if you CTRL_RIGHT and then CTRL_LEFT, the cursor would move the view after you do CTRL_LEFT and the cursor would be inside line numbers. This ONLY happens when you save with the cursor at col 0 on the line with the really long word. This is now resolved.

Steps to reproduce either of these bugs:
1. Create a new file that looks like this
```
First line
ReallyLongWordHereThatGoesPastTheEndOfTheScreenAndMovesTheView...............................................
```
2. Put the cursor in front of the 2nd line so that it is before the letter "R" in "Really". It should look like this.
```
First line
|ReallyLongWordHereThatGoesPastTheEndOfTheScreenAndMovesTheView...............................................
```
3. Save the file, then reopen the file
4. CTRL_RIGHT, then CTRL_LEFT. Observe the cursor position. To produce the other bug, you can hold the right arrow key until you move the view to the right. Then hold the left arrow key until scrollCol = 1.
One more left arrow key should move the cursor into the line numbers section.

**Comment by dschuyler** [comment] 2017-10-19 17:44
Thanks. So it sounds like I can close this?

**Comment by aaxu** [comment] 2017-10-19 18:41
Yep!

**Closed** 2017-10-23 17:12 UTC
Labels: bug
